### ISSUE TITLE
Error when installing: Do not leave the Address field blank

### ISSUE THREAD

**Issue by kpaulisse** [rapid7/puppet-nexpose#5]
I'm trying to use this module to set up nexpose and when I run it I get this message:

```
Do not leave the Address field blank
```

The installation fails. Is there a new variable that needs to go into the response file that has not yet made it into the template in this repo?

**Comment by helenes-r7** [comment]
Hey @kpaulisse 

Yep you are correct that a new variable needs to go into the response file, currently looking at what that might be.
Nexpose should still install though, the message you get should only be a warning but not fail the installation. The service might fail to start on the first Puppet run, but another Puppet run should start it successfully. Can you confirm?

**Comment by kpaulisse** [comment]
The command exits with status 1, which in our tooling causes Puppet to indicate that provisioning has failed.

Poking around a bit, it seems that "consoleAddress" and "sharedSecret" are the two parameters that we need to set in there, but I could not find documentation on what these do. I tried setting consoleAddress to `localhost` and sharedSecret to `kittens` which brings up this:

```
In screen "Console details [CustomFormPanelScreen]", property "Validation expression":
java.util.MissingResourceException: Can't find resource for bundle com.install4j.runtime.util.FileResourceBundle, key EngineConsoleTestunuccessful
	at java.util.ResourceBundle.getObject(ResourceBundle.java:450)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:444)
	at com.install4j.runtime.installer.frontend.VariableResourceBundleWrapper.handleGetObject(VariableResourceBundleWrapper.java:32)
	at java.util.ResourceBundle.getObject(ResourceBundle.java:441)
	at java.util.ResourceBundle.getString(ResourceBundle.java:407)
	at com.install4j.runtime.installer.ContextImpl.getMessage(ContextImpl.java:349)
	at com.install4j.script.I4jScript_Internal_203.eval(I4jScript_Internal_203.java:212)
	at com.install4j.script.I4jScript_Internal_203.evaluate(I4jScript_Internal_203.java:242)
	at com.install4j.runtime.installer.helper.Script.evaluate(Script.java:33)
	at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:188)
	at com.install4j.runtime.installer.ContextImpl.runScript(ContextImpl.java:182)
	at com.install4j.runtime.installer.ContextImpl.runBooleanScript(ContextImpl.java:55)
	at com.install4j.runtime.installer.ContextImpl.runBooleanScript(ContextImpl.java:225)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.runValidationScript(AbstractHeadlessScreenExecutor.java:124)
	at com.install4j.runtime.installer.frontend.headless.UnattendedScreenExecutor.handleScreen(UnattendedScreenExecutor.java:100)
	at com.install4j.runtime.installer.frontend.headless.AbstractHeadlessScreenExecutor.execute(AbstractHeadlessScreenExecutor.java:81)
	at com.install4j.runtime.installer.controller.Controller$1.run(Controller.java:138)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I'm not sure if it's because of an apparent typo in "EngineConsoleTestunuccessful" or more likely if this is because it's trying to test communication between services that haven't been registered yet or started up. Maybe there's a boolean flag that we can set to disable this connectivity test during an unattended install?

**Comment by helenes-r7** [comment]
Hmm interesting... can you provide the Puppet code? redacting any sensitive info

**Comment by kpaulisse** [comment]
I just added this to the end of the `response.varfile.erb` template:

```
# Undocumented Parameters - Fix/parameterize these when we know what they do
consoleAddress=localhost
sharedSecret=kittens
```

**Comment by chunyong-lin** [comment]
Hi  @helenes-r7 
I also encounter same issue with output `Do not leave the Address field blank` and chef installation exists with code `1`(I am using nexpose chef cookbook to install scan engine.)
Do you know what're the variables am I missing?

**Comment by moezthemaster** [comment]
same problem as kpaulisse . is there any fix?
